### login
POST http://127.0.0.1:8000/rest-auth/login/ HTTP/1.1
Content-Type: application/json

{
    "email": "thien@gmail.com",
    "password": "test8888"
}

###
GET http://127.0.0.1:8000/assignments/list/ HTTP/1.1
Content-Type: application/json
Authorization: Token f17458a9741fa9e1fb608aa4e43b0c963887a1d7



###
POST http://127.0.0.1:8000/assignments/ HTTP/1.1
Content-Type: application/json
Authorization: Token f17458a9741fa9e1fb608aa4e43b0c963887a1d7

{
  "questions_of_assignment": [
    {
        "question_title": "Updated Is it hot?",
        "choices_of_question": [
            {"choice_title": "Its hot"},
            {"choice_title": "No, Its not"}
            ],
        "answer_of_question": {"answer": 2},
        "order": 1
    },
    {
        "question_title": "Updated Is it cold?",
        "choices_of_question": [
            {"choice_title": "Yes it is "},
            {"choice_title": "No it not"}
            ],
        "answer_of_question": {"answer": 4},
        "order": 2
    }
    ],
  "title": "The real Assignment 5",
  "teacher": 2
}



###
GET http://127.0.0.1:8000/assignments/teacher/2/ HTTP/1.1
Content-Type: application/json
Authorization: Token f17458a9741fa9e1fb608aa4e43b0c963887a1d7

### register
POST http://127.0.0.1:8000/myaccounts/register HTTP/1.1
Content-Type: application/json

{
    "email": "thien8@gmail.com",
    "first_name": "Th",
    "last_name": "Ng",
    "department": "Py",
    "phone": "8877999",
    "password": "test8888",
    "password2": "test8888",
    "profile": {
        "student_id": "222"
    },
    "date_of_birth": "2000-05-05",
    "is_teacher": true,
    "is_student": false
}


###
POST http://127.0.0.1:8000/assignments/taker/4/ HTTP/1.1
Content-Type: application/json
Authorization: Token 3785f0eebb160b6181cd8842ce823d4fd352c8b6

{
  "questions_of_assignment": [
    {
      "id": 6,
      "choices_of_question": [
        {
          "choice_title": "Its hot"
        },
        {
          "choice_title": "No, Its not"
        }
      ],
      "question_title": "Is it hot?",
      "order": 1,
      "assignment": 4
    },
    {
      "id": 7,
      "choices_of_question": [
        {
          "choice_title": "Yes it is"
        },
        {
          "choice_title": "No it not"
        }
      ],
      "answer_of_question": {
        "answer": 2
      },
      "question_title": "Is it cold?",
      "order": 2,
      "assignment": 4
    }
  ],
  "grade": 0,
  "student": 3
}



###
GET http://127.0.0.1:8000/assignments/taker/3 HTTP/1.1
Content-Type: application/json
Authorization: Token 3785f0eebb160b6181cd8842ce823d4fd352c8b6


###
POST http://127.0.0.1:8000/assignments/completed/4/ HTTP/1.1
Content-Type: application/json
Authorization: Token 3785f0eebb160b6181cd8842ce823d4fd352c8b6


### register
GET http://127.0.0.1:8000/myaccounts/profile/3/ HTTP/1.1
Authorization: Token 3785f0eebb160b6181cd8842ce823d4fd352c8b6