# Generated by Django 3.1.1 on 2020-10-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedassignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
