# Generated by Django 3.1.1 on 2020-10-10 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_gradedassignment_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedassignment',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignment', to='assignments.assignment'),
        ),
        migrations.AlterField(
            model_name='gradedassignment',
            name='grade',
            field=models.FloatField(default=0),
        ),
    ]
