# Generated by Django 3.1.1 on 2020-10-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20201005_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ManyToManyField(related_name='choices_of_question', to='assignments.Question'),
        ),
    ]
