# Generated by Django 3.1.1 on 2020-10-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20201005_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ManyToManyField(to='assignments.Question'),
        ),
    ]
