# Generated by Django 3.1.1 on 2020-10-11 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0004_auto_20201011_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='myaccounts.myuser'),
            preserve_default=False,
        ),
    ]
