# Generated by Django 3.1.1 on 2020-10-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_studentanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
