# Generated by Django 3.1.1 on 2020-10-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_auto_20201021_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='choice_of_answer',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answer_of_student',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='choices_of_question',
            field=models.ManyToManyField(to='assignments.Choice'),
        ),
    ]
