# Generated by Django 3.1.1 on 2020-10-22 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0016_auto_20201022_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='choices_of_question',
        ),
    ]
