# Generated by Django 3.1.1 on 2020-10-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0017_remove_studentanswer_choices_of_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
