# Generated by Django 3.1.1 on 2020-10-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0020_auto_20201022_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='question',
        ),
    ]
