# Generated by Django 3.1.1 on 2020-10-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0021_remove_studentanswer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='answer_of_student',
            new_name='answer_text',
        ),
    ]
