# Generated by Django 3.1.1 on 2020-10-22 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0022_auto_20201022_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
