# Generated by Django 3.1.1 on 2020-10-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0023_auto_20201022_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedassignment',
            name='answer_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
